kind: pipeline
type: docker
name: deploy-servertool

labels:
  type: builder

steps:
  # 1. Build and push Backend
  - name: publish-backend
    image: plugins/kaniko
    settings:
      repo: eugenekallis/servertoolpython-backend
      tags: ${CI_COMMIT_SHA:0:8}
      dockerfile: backend/Dockerfile
      context: backend
      cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  # 2. Build and push Frontend
  - name: publish-frontend
    image: plugins/kaniko
    settings:
      repo: eugenekallis/servertoolpython-frontend
      tags: ${CI_COMMIT_SHA:0:8}
      dockerfile: frontend/Dockerfile
      context: frontend
      cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  # 3. Build and push Agent
  - name: publish-agent
    image: plugins/kaniko
    settings:
      repo: eugenekallis/servertoolpython-agent
      tags: ${CI_COMMIT_SHA:0:8}
      dockerfile: agent/Dockerfile
      context: agent
      cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - main
  event:
    - push
