"""add shell_history table

Revision ID: 1143324f379b
Revises: 4bb75d8ed3a1
Create Date: 2026-03-29 10:29:23.482186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1143324f379b'
down_revision: Union[str, Sequence[str], None] = '4bb75d8ed3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shell_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shell_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shell_history')
    # ### end Alembic commands ###
