"""add macrogroup hierarchy

Revision ID: 2959af308afc
Revises: e2d0cb685e97
Create Date: 2026-03-10 10:21:43.566641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2959af308afc'
down_revision: Union[str, Sequence[str], None] = 'e2d0cb685e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('macro', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_macro_macro_group_id_macro_group'), 'macro_group', ['macro_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('macro', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_macro_macro_group_id_macro_group'), type_='foreignkey')

    # ### end Alembic commands ###
