"""add scraped_item and scraped_item_file tables

Revision ID: 4bb75d8ed3a1
Revises: 8168eeb21d96
Create Date: 2026-03-27 11:05:42.974855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb75d8ed3a1'
down_revision: Union[str, Sequence[str], None] = '8168eeb21d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arr_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arr_instance')),
    sa.UniqueConstraint('name', name=op.f('uq_arr_instance_name'))
    )
    op.create_table('chat_conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_conversation'))
    )
    op.create_table('scraped_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('magnet_link', sa.String(), nullable=False),
    sa.Column('torrent_link', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_downloaded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scraped_item'))
    )
    with op.batch_alter_table('scraped_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraped_item_magnet_link'), ['magnet_link'], unique=True)
        batch_op.create_index(batch_op.f('ix_scraped_item_source'), ['source'], unique=False)

    op.create_table('script_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('macro_name', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_run'))
    )
    with op.batch_alter_table('script_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_script_run_macro_name'), ['macro_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_script_run_run_id'), ['run_id'], unique=True)

    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], name=op.f('fk_chat_message_conversation_id_chat_conversation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    op.create_table('scraped_item_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('magnet_link', sa.String(), nullable=False),
    sa.Column('file_size', sa.String(), nullable=True),
    sa.Column('seeds', sa.Integer(), nullable=True),
    sa.Column('leechers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['scraped_item.id'], name=op.f('fk_scraped_item_file_item_id_scraped_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scraped_item_file'))
    )
    with op.batch_alter_table('scraped_item_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraped_item_file_magnet_link'), ['magnet_link'], unique=True)

    op.create_table('macro_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('macro_id', sa.Integer(), nullable=False),
    sa.Column('cron_expression', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('args', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['macro_id'], ['macro.id'], name=op.f('fk_macro_schedule_macro_id_macro')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_macro_schedule'))
    )
    op.create_table('command_argument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arg_name', sa.String(), nullable=False),
    sa.Column('arg_value', sa.String(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['command.id'], name=op.f('fk_command_argument_command_id_command')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_command_argument'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command_argument')
    op.drop_table('macro_schedule')
    with op.batch_alter_table('scraped_item_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraped_item_file_magnet_link'))

    op.drop_table('scraped_item_file')
    op.drop_table('chat_message')
    with op.batch_alter_table('script_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_script_run_run_id'))
        batch_op.drop_index(batch_op.f('ix_script_run_macro_name'))

    op.drop_table('script_run')
    with op.batch_alter_table('scraped_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraped_item_source'))
        batch_op.drop_index(batch_op.f('ix_scraped_item_magnet_link'))

    op.drop_table('scraped_item')
    op.drop_table('chat_conversation')
    op.drop_table('arr_instance')
    # ### end Alembic commands ###
