"""remove_name_from_command

Revision ID: 8168eeb21d96
Revises: 2959af308afc
Create Date: 2026-03-15 14:10:37.602397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8168eeb21d96'
down_revision: Union[str, Sequence[str], None] = '2959af308afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_name'), if_exists=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_command_name'), ['name'], unique=False)

    # ### end Alembic commands ###
