"""remove_name_from_command

Revision ID: 8168eeb21d96
Revises: 2959af308afc
Create Date: 2026-03-15 14:10:37.602397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8168eeb21d96'
down_revision: Union[str, Sequence[str], None] = '2959af308afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop name column if it exists (PostgreSQL supports IF EXISTS for DROP COLUMN)
    op.execute("ALTER TABLE command DROP COLUMN IF EXISTS name")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add name column back only if it doesn't exist
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='command' AND column_name='name') THEN
                ALTER TABLE command ADD COLUMN name VARCHAR NOT NULL DEFAULT '';
            END IF;
        END $$;
    """)
    # Recreate index only if it doesn't exist
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_command_name') THEN
                CREATE INDEX ix_command_name ON command (name);
            END IF;
        END $$;
    """)
