kind: pipeline
type: docker
name: dev-deploy

labels:
  type: builder

steps:
  - name: build-frontend
    image: plugins/kaniko
    when:
      branch: develop
      event: [ push, manual ]
    settings:
      repo: eugenekallis/servertoolpython-frontend
      tags: dev-${CI_COMMIT_SHA:0:8}
      dockerfile: frontend/Dockerfile
      context: frontend
      cache: true
      cache_repo: eugenekallis/servertoolpython-frontend-cache
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: build-backend
    image: plugins/kaniko
    when:
      branch: develop
      event: [ push, manual ]
    settings:
      repo: eugenekallis/servertoolpython-backend
      tags: dev-${CI_COMMIT_SHA:0:8}
      dockerfile: backend/Dockerfile
      context: backend
      cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: build-agent
    image: plugins/kaniko
    when:
      branch: develop
      event: [ push, manual ]
    settings:
      repo: eugenekallis/servertoolpython-agent
      tags: dev-${CI_COMMIT_SHA:0:8}
      dockerfile: agent/Dockerfile
      context: agent
      cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy-dev
    image: alpine:latest
    when:
      branch: develop
      event: [ push, manual ]
    commands:
      - apk add --no-cache git yq openssh-client
      - mkdir -p ~/.ssh
      - echo "$GIT_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan github.com >> ~/.ssh/known_hosts
      - git clone git@github.com:EugeneKallis/kubernetes-cluster.git infra
      - cd infra
      - 'yq -i ".global.image.tag = \"dev-${CI_COMMIT_SHA:0:8}\"" charts/servertool-python/values-dev.yaml'
      - git add .
      - git config user.name "Woodpecker CI"
      - git config user.email "woodpecker@cluster.lan"
      - 'git commit -m "chore: deploy dev ${CI_COMMIT_SHA:0:8}"'
      - git push origin main
    environment:
      GIT_SSH_KEY:
        from_secret: git_ssh_key
    depends_on:
      - build-frontend
      - build-backend
      - build-agent
