kind: pipeline
type: docker
name: prod-deploy

labels:
  type: builder

steps:
  # 1. Build and push Backend
  - name: publish-backend
    image: plugins/kaniko
    when:
      branch: main
      event: [ push, manual ]
    settings:
      repo: eugenekallis/servertoolpython-backend
      tags: ${CI_COMMIT_SHA:0:8}
      dockerfile: backend/Dockerfile
      context: backend
      cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  # 2. Build and push Frontend
  - name: publish-frontend
    image: plugins/kaniko
    when:
      branch: main
      event: [ push, manual ]
    settings:
      repo: eugenekallis/servertoolpython-frontend
      tags: ${CI_COMMIT_SHA:0:8}
      dockerfile: frontend/Dockerfile
      context: frontend
      cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  # 3. Build and push Agent
  - name: publish-agent
    image: plugins/kaniko
    when:
      branch: main
      event: [ push, manual ]
    settings:
      repo: eugenekallis/servertoolpython-agent
      tags: ${CI_COMMIT_SHA:0:8}
      dockerfile: agent/Dockerfile
      context: agent
      cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  # 4. Deploy to Production
  - name: deploy-prod
    image: alpine:latest
    when:
      branch: main
      event: [ push, manual ]
    commands:
      - apk add --no-cache git yq openssh-client
      - mkdir -p ~/.ssh
      - echo "$GIT_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan github.com >> ~/.ssh/known_hosts
      - git clone git@github.com:eugenekallis/kubernetes-cluster.git infra
      - cd infra
      - 'yq -i ".global.image.tag = \"${CI_COMMIT_SHA:0:8}\"" charts/servertool-python/values-prod.yaml'
      - git add .
      - git config user.name "Woodpecker CI"
      - git config user.email "woodpecker@cluster.lan"
      - 'git commit -m "chore: deploy prod ${CI_COMMIT_SHA:0:8}"'
      - git push origin main
    environment:
      GIT_SSH_KEY:
        from_secret: git_ssh_key
    depends_on:
      - publish-backend
      - publish-frontend
      - publish-agent
